FROM n8nio/n8n:latest

# Expose the Railway port
EXPOSE ${PORT}

# Use Railway's PORT
ENV N8N_PORT=${PORT}
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=Yousef_2025!@#
ENV N8N_HOST=0.0.0.0

CMD ["n8n"]
